// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ox4sDatabase.Server;

#nullable disable

namespace ox4sDatabase.Server.Migrations
{
    [DbContext(typeof(DbContext))]
    partial class DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ox4sDatabase.Shared.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlternativArtikelNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bemerkungen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Breite")
                        .HasColumnType("float");

                    b.Property<string>("Einheit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EinheitsPreis_1_Netto")
                        .HasColumnType("float");

                    b.Property<double>("EinheitsPreis_2_Netto")
                        .HasColumnType("float");

                    b.Property<string>("ExternerLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hersteller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HerstellerArtikelNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Hoehe")
                        .HasColumnType("float");

                    b.Property<string>("InternerLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KurzName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LagerPlatz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LangName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LieferZeit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lieferant_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lieferant_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lieferant_3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lieferant_4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lieferant_5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lieferant_6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lieferant_7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LieferantenArtikelNummer_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LieferantenArtikelNummer_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rabatt")
                        .HasColumnType("float");

                    b.Property<double>("RabattierterNettoPreis")
                        .HasColumnType("float");

                    b.Property<double>("Tiefe")
                        .HasColumnType("float");

                    b.Property<double>("UmgebungstemperaturBetrieb")
                        .HasColumnType("float");

                    b.Property<double>("VK_10")
                        .HasColumnType("float");

                    b.Property<double>("VK_15")
                        .HasColumnType("float");

                    b.Property<double>("VK_20")
                        .HasColumnType("float");

                    b.Property<string>("VPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
